[package]
name = "paa-gimp-rs"
version = "0.1.0"
author = "fixitdaztv"
date = "2026-02-13"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
binrw = "0.13"
anyhow = "1.0"
image = "0.24"
squish = "1.0.0"
minilzo-rs = "0.6.0"